#!/usr/bin/env python3
# tools/gen_hrtf_header.py
#
# Converts the SADIE II D2 (KU100) 48kHz HRIR WAV files into a C++ header.
# Run once from the project root:
#
#   pip install numpy scipy
#   python tools/gen_hrtf_header.py
#
# Output: src/hrtf_data.h

import os
import re
import numpy as np
from scipy.io import wavfile

# -----------------------------------------------------------------------
# configuration
# -----------------------------------------------------------------------
HRIR_DIR = "data/SADIE2/D2/D2_HRIR_WAV/48K_24bit"
OUTPUT_FILE = "src/hrtf_data.h"
IR_LENGTH = 256  # samples to keep per IR — SADIE II at 48k is typically 512+
# we truncate to 256 which captures the perceptually important
# early portion (ITD + ILD + pinna). increase if you want more
# low-frequency accuracy at the cost of convolution expense.
# -----------------------------------------------------------------------


def parse_filename(filename):
    """
    Parse azimuth and elevation from a filename like:
        azi_336,0_ele_-45,0.wav
    Returns (azimuth_float, elevation_float) or None if parsing fails.
    Commas are used as decimal separators in SADIE II filenames.
    """
    pattern = r"azi_([-\d]+,\d+)_ele_([-\d]+,\d+)\.wav"
    match = re.match(pattern, filename)
    if not match:
        return None
    az_str = match.group(1).replace(",", ".")
    el_str = match.group(2).replace(",", ".")
    return float(az_str), float(el_str)


def convert_sadie_azimuth(az):
    """
    SADIE II measures azimuth anti-clockwise (to the left).
    Standard audio convention is clockwise (to the right).
    Convert: negate and wrap to [0, 360).
    e.g. SADIE 90° (left) -> standard 270° (left)
         SADIE 270° (right) -> standard 90° (right)
    """
    return (-az) % 360.0


def fit_length(ir, length):
    """Truncate or zero-pad IR to exactly `length` samples."""
    if len(ir) >= length:
        return ir[:length].copy()
    return np.pad(ir, (0, length - len(ir))).astype(np.float32)


# -----------------------------------------------------------------------
# read all WAV files
# -----------------------------------------------------------------------
print(f"scanning {HRIR_DIR} ...")

directions = []  # list of (azimuth_std, elevation, left_ir, right_ir)
skipped = 0

for filename in sorted(os.listdir(HRIR_DIR)):
    if not filename.endswith(".wav"):
        continue

    parsed = parse_filename(filename)
    if parsed is None:
        print(f"  warning: could not parse '{filename}', skipping")
        skipped += 1
        continue

    az_sadie, elevation = parsed

    # convert azimuth to standard clockwise convention
    azimuth = convert_sadie_azimuth(az_sadie)

    filepath = os.path.join(HRIR_DIR, filename)
    sr, data = wavfile.read(filepath)

    # SADIE II 48K_24bit files are 24-bit int stored as int32 by scipy
    # normalise to float32 in [-1.0, 1.0]
    if data.dtype == np.int32:
        data = data.astype(np.float32) / 2147483648.0
    elif data.dtype == np.int16:
        data = data.astype(np.float32) / 32768.0
    elif data.dtype == np.float32 or data.dtype == np.float64:
        data = data.astype(np.float32)

    # data shape should be (num_samples, 2) — stereo L/R
    if data.ndim != 2 or data.shape[1] != 2:
        print(f"  warning: unexpected shape {data.shape} in '{filename}', skipping")
        skipped += 1
        continue

    left_ir = fit_length(data[:, 0].astype(np.float32), IR_LENGTH)
    right_ir = fit_length(data[:, 1].astype(np.float32), IR_LENGTH)

    directions.append((azimuth, elevation, left_ir, right_ir))

print(f"loaded {len(directions)} directions  ({skipped} skipped)")

if len(directions) == 0:
    print("ERROR: no directions loaded — check HRIR_DIR path")
    exit(1)

# sort by elevation then azimuth for predictable indexing
directions.sort(key=lambda d: (d[1], d[0]))

# -----------------------------------------------------------------------
# write C++ header
# -----------------------------------------------------------------------
N = len(directions)
print(f"writing {OUTPUT_FILE} ...")

with open(OUTPUT_FILE, "w") as f:
    f.write("// hrtf_data.h\n")
    f.write("// Auto-generated by tools/gen_hrtf_header.py\n")
    f.write("// Source: SADIE II Database, D2 KU100, 48kHz 24-bit\n")
    f.write("// https://zenodo.org/records/10886409\n")
    f.write("// License: Apache 2.0\n")
    f.write("// DO NOT EDIT BY HAND\n")
    f.write("//\n")
    f.write("// Azimuth convention: clockwise from front (standard audio)\n")
    f.write("//   0°   = front\n")
    f.write("//   90°  = right\n")
    f.write("//   180° = behind\n")
    f.write("//   270° = left\n")
    f.write("//\n")
    f.write(f"// {N} directions, {IR_LENGTH} samples per IR, 2 ears\n")
    f.write(f"// table size: {N * 2 * IR_LENGTH * 4 / 1024:.1f} KB\n")
    f.write("\n")
    f.write("#pragma once\n")
    f.write("\n")
    f.write(f"static const int HRTF_IR_LENGTH    = {IR_LENGTH};\n")
    f.write(f"static const int HRTF_N_DIRECTIONS = {N};\n")
    f.write("\n")

    # direction metadata struct
    f.write("struct HrtfDirection {\n")
    f.write("    float azimuth;    // degrees, clockwise from front, [0, 360)\n")
    f.write("    float elevation;  // degrees, positive = above horizon\n")
    f.write("};\n")
    f.write("\n")

    # direction lookup table
    f.write(f"static const HrtfDirection hrtf_directions[HRTF_N_DIRECTIONS] = {{\n")
    for az, elev, _, _ in directions:
        f.write(f"    {{ {az:.1f}f, {elev:.1f}f }},\n")
    f.write("};\n")
    f.write("\n")

    # IR data — [direction][ear][sample]
    # ear 0 = left, ear 1 = right
    f.write("// hrtf_irs[direction][ear][sample]\n")
    f.write("// ear: 0 = left, 1 = right\n")
    f.write(f"static const float hrtf_irs[HRTF_N_DIRECTIONS][2][HRTF_IR_LENGTH] = {{\n")

    for idx, (az, elev, left_ir, right_ir) in enumerate(directions):
        f.write(f"    // [{idx}]  azimuth={az:.1f}°  elevation={elev:.1f}°\n")
        f.write("    {\n")

        # left ear
        f.write("        {")
        f.write(", ".join(f"{v:.8f}f" for v in left_ir))
        f.write("},\n")

        # right ear
        f.write("        {")
        f.write(", ".join(f"{v:.8f}f" for v in right_ir))
        f.write("},\n")

        f.write("    },\n")

    f.write("};\n")
    f.write("\n")

    # helper function inline in the header for finding the closest direction
    f.write("// find_closest_hrtf -- returns the direction index whose azimuth\n")
    f.write("// and elevation are closest to the requested values.\n")
    f.write("// Call at startup to pick HRTF indices for virtual speaker positions.\n")
    f.write("// azimuth: clockwise from front [0, 360)\n")
    f.write("// elevation: degrees above/below horizon\n")
    f.write("inline int find_closest_hrtf(float azimuth, float elevation) {\n")
    f.write("    int   best_idx  = 0;\n")
    f.write("    float best_dist = 1e9f;\n")
    f.write("    for (int i = 0; i < HRTF_N_DIRECTIONS; i++) {\n")
    f.write("        float da = hrtf_directions[i].azimuth   - azimuth;\n")
    f.write("        float de = hrtf_directions[i].elevation - elevation;\n")
    f.write("        // wrap azimuth difference to [-180, 180]\n")
    f.write("        if (da >  180.0f) da -= 360.0f;\n")
    f.write("        if (da < -180.0f) da += 360.0f;\n")
    f.write("        float dist = da*da + de*de;\n")
    f.write("        if (dist < best_dist) {\n")
    f.write("            best_dist = dist;\n")
    f.write("            best_idx  = i;\n")
    f.write("        }\n")
    f.write("    }\n")
    f.write("    return best_idx;\n")
    f.write("}\n")

table_kb = N * 2 * IR_LENGTH * 4 / 1024
print(f"done — {N} directions, table size {table_kb:.1f} KB")
print(f"output: {OUTPUT_FILE}")
